
# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(openxlsx)
library(readxl)
library(dplyr)
library(ggplot2)
library(caret)
library(pROC)
library(gbm)
library(randomForest)
library(MASS)
library(performanceEstimation)
library(class)

# Set seed
set.seed(123)

results <- data.frame(
  Model = character(),
  Accuracy = numeric(),
  Precision = numeric(),
  Recall = numeric(),
  AOC = numeric(),
  stringsAsFactors = FALSE
)

# Define theme colors
primary_color = "#191919ff"
secondary_color = "#c67812ff"
```

# Load the data
```{r data_loading}
train_set <- read_excel("../data/hotel_data_balanced_train.xlsx")
test_set <- read_excel("../data/hotel_data_balanced_test.xlsx")

# Factorizing and normalizing
numerical_names <- c(
  "LeadTime", 
  "PreviousBookingsNotCanceled", 
  "StaysInWeekendNights", 
  "StaysInWeekNights", 
  "Adults", 
  "Children", 
  "Babies", 
  "BookingChanges", 
  "DaysInWaitingList",
  "TotalOfSpecialRequests"
)

train_set_numerical <- train_set %>% dplyr::select(numerical_names)
train_set_categorical <- train_set %>% dplyr::select(-one_of(numerical_names))

test_set_numerical <- test_set %>% dplyr::select(numerical_names)
test_set_categorical <- test_set %>% dplyr::select(-one_of(numerical_names))

# Factorize everything except for the LeadTime and PreviousCancellations variables
# Use a loop
for (i in 1:ncol(train_set_categorical)) {
  train_set_categorical[[i]] <- as.factor(train_set_categorical[[i]])
}

for (i in 1:ncol(train_set_categorical)) {
  test_set_categorical[[i]] <- as.factor(test_set_categorical[[i]])
}


# Normalize the numerical variables
train_set_numerical <- scale(train_set_numerical)
test_set_numerical <- scale(test_set_numerical)

# Merge data back together
train_set <- cbind(train_set_numerical, train_set_categorical)
test_set <- cbind(test_set_numerical, test_set_categorical)

class_balance <- prop.table(table(train_set$IsCanceled))
threshold <- class_balance[2]
```

# K-Nearest Neighbors Setup
```{r knn_setup}

myCtrl <- trainControl(method = "cv", number = 10)
myGrid <- expand.grid(.k=c(1:15))

```

# K-Nearest Neighbors Model with All Variables
```{r knn_full_model}

knn_full_model <- train(
  IsCanceled ~ ., 
  data = train_set,
  method = "knn",
  trControl = myCtrl,
  tuneGrid = myGrid
)

summary(knn_full_model)

knn_full_model_p <- predict(knn_full_model, newdata = test_set, type = "prob")
knn_full_model_y <- ifelse(knn_full_model_p[,2] > threshold, 1, 0) 

# Confusion matrix
confusion_matrix <- table(test_set$IsCanceled, knn_full_model_y)

# Accuracy, Precision and Recall
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
precision <- confusion_matrix[2, 2] / sum(confusion_matrix[, 2])
recall <- confusion_matrix[2, 2] / sum(confusion_matrix[2, ])

cat("Accuracy", accuracy, "\n")
cat("Precision: ", precision, "\n")
cat("Recall: ", recall, "\n")


# Generate AOC curve
roc_curve <- roc(test_set$IsCanceled, knn_full_model_p[,2])
aoc <- auc(roc_curve)
aoc

p <- ggroc(
  roc_curve, 
  col = secondary_color,
  lwd = 2,
) +
  geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="grey", linetype="dashed") +
  theme(panel.background = element_rect(fill = "transparent")) +
  theme_minimal() +
  # Add AUC to the plot
  annotate(
    "text",
    x = 0.8,
    y = 1,
    label = paste("AUC:", round(aoc, 2)),
    size = 5,
    color = secondary_color
  )

p

ggsave(
  plot = p,
  filename = "./plots/modeling_knn_full_roc.png",
  bg = "transparent"
)

# Add to results
results <- rbind(
  results,
  data.frame(
    Model = "KNN",
    Accuracy = round(accuracy, 3),
    Precision = round(precision, 3),
    Recall = round(recall, 3),
    AOC = round(aoc, 3)
  )
)

```


# K-Nearest Neighbors Model with Variables Selected from Forward Stepwise
```{r knn_full_model}

knn_subset_model <- train(
  IsCanceled ~ 
    MarketSegment + 
    LeadTime + 
    BookingChanges + 
    CustomerType + 
    DepositType,
  data = train_set,
  method = "knn",
  trControl = myCtrl,
  tuneGrid = myGrid
)

summary(knn_subset_model)

knn_subset_model_p <- predict(knn_subset_model, newdata = test_set, type = "prob")
knn_subset_model_y <- ifelse(knn_subset_model_p[,2] > 0.4, 1, 0) 

# Confusion matrix
confusion_matrix <- table(test_set$IsCanceled, knn_subset_model_y)

# Accuracy, Precision and Recall
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
precision <- confusion_matrix[2, 2] / sum(confusion_matrix[, 2])
recall <- confusion_matrix[2, 2] / sum(confusion_matrix[2, ])

cat("Accuracy", accuracy, "\n")
cat("Precision: ", precision, "\n")
cat("Recall: ", recall, "\n")

# Generate AOC curve
roc_curve <- roc(test_set$IsCanceled, knn_subset_model_p[,2])
aoc <- auc(roc_curve)
aoc

p <- ggroc(
  roc_curve, 
  col = secondary_color,
  lwd = 2,
) +
  geom_segment(aes(x = 1, xend = 0, y = 0, yend = 1), color="grey", linetype="dashed") +
  theme(panel.background = element_rect(fill = "transparent")) +
  theme_minimal() +
  # Add AUC to the plot
  annotate(
    "text",
    x = 0.8,
    y = 1,
    label = paste("AUC:", round(aoc, 2)),
    size = 5,
    color = secondary_color
  )

p

ggsave(
  plot = p,
  filename = "./plots/modeling_knn_subset_roc.png",
  bg = "transparent"
)

# Add to results
results <- rbind(
  results,
  data.frame(
    Model = "KNN",
    Accuracy = round(accuracy, 3),
    Precision = round(precision, 3),
    Recall = round(recall, 3),
    AOC = round(aoc, 3)
  )
)

```

```{r results}

results

```
